set_property CFGBVS VCCO [current_design]
set_property CONFIG_VOLTAGE 3.3 [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {buttons[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {buttons[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {buttons[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {buttons[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {buttons[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {buttons[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {buttons[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {buttons[0]}]
set_property PACKAGE_PIN M16 [get_ports {buttons[0]}]
set_property PACKAGE_PIN M15 [get_ports {buttons[1]}]
set_property PACKAGE_PIN N16 [get_ports {buttons[2]}]
set_property PACKAGE_PIN P16 [get_ports {buttons[3]}]
set_property PACKAGE_PIN P15 [get_ports {buttons[4]}]
set_property PACKAGE_PIN R16 [get_ports {buttons[5]}]
set_property PACKAGE_PIN R15 [get_ports {buttons[6]}]
set_property PACKAGE_PIN T15 [get_ports {buttons[7]}]

set_property IOSTANDARD LVCMOS33 [get_ports {segDecoded[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {segDecoded[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {segDecoded[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {segDecoded[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {segDecoded[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {segDecoded[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {segDecoded[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {segDecoded[0]}]
set_property PACKAGE_PIN C16 [get_ports {segDecoded[0]}]
set_property PACKAGE_PIN D15 [get_ports {segDecoded[1]}]
set_property PACKAGE_PIN E15 [get_ports {segDecoded[2]}]
set_property PACKAGE_PIN A14 [get_ports {segDecoded[3]}]
set_property PACKAGE_PIN B15 [get_ports {segDecoded[4]}]
set_property PACKAGE_PIN B16 [get_ports {segDecoded[5]}]
set_property PACKAGE_PIN A15 [get_ports {segDecoded[6]}]
set_property PACKAGE_PIN D16 [get_ports {segDecoded[7]}]
