set_property PACKAGE_PIN M16 [get_ports l_door]
set_property PACKAGE_PIN M15 [get_ports r_door]
set_property PACKAGE_PIN J1 [get_ports lamp]
set_property IOSTANDARD LVCMOS33 [get_ports l_door]
set_property IOSTANDARD LVCMOS33 [get_ports lamp]
set_property IOSTANDARD LVCMOS33 [get_ports r_door]
set_property CONFIG_VOLTAGE 3.3 [current_design]
set_property CFGBVS VCCO [current_design]
set_property SLEW SLOW [get_ports lamp]

set_property PACKAGE_PIN F15 [get_ports {lights[7]}]
set_property PACKAGE_PIN C14 [get_ports {lights[5]}]

set_property IOSTANDARD LVCMOS33 [get_ports light1]
set_property IOSTANDARD LVCMOS33 [get_ports light2]
set_property IOSTANDARD LVCMOS33 [get_ports {lights[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {lights[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {lights[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {lights[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {lights[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {lights[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {lights[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {lights[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports toggle]
set_property PACKAGE_PIN D1 [get_ports {lights[0]}]
set_property PACKAGE_PIN B4 [get_ports {lights[1]}]
set_property PACKAGE_PIN A7 [get_ports {lights[2]}]
set_property PACKAGE_PIN B9 [get_ports {lights[3]}]
set_property PACKAGE_PIN B14 [get_ports {lights[4]}]
set_property PACKAGE_PIN E16 [get_ports {lights[6]}]
set_property PACKAGE_PIN P16 [get_ports light1]
set_property PACKAGE_PIN P15 [get_ports light2]
set_property PACKAGE_PIN T15 [get_ports toggle]
